force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>訪問</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000}</displayFormat>
        <label>訪問名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/EndDatetime__c.field-meta.xml
<CustomField>
    <fullName>EndDatetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>終了時刻</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>予定</fullName>
                <default>true</default>
                <label>予定</label>
            </value>
            <value>
                <fullName>訪問中</fullName>
            </value>
            <value>
                <fullName>終了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
            <value>
                <fullName>日程変更</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VisitTriggerHandler.cls
public with sharing class VisitTriggerHandler {
    public VisitTriggerHandler() {
    }

    /**
     * before insert
     */
    public void onBeforeInsert(List<Visit__c> newList){
    }

    /**
     * before insert
     */
    public void onBeforeUpdate(Map<Id, Visit__c> newMap, Map<Id, Visit__c> oldMap){
        for(String key : newMap.keySet()){
            Visit__c newObj = newMap.get(key);
            Visit__c oldObj = oldMap.get(key);

            if(newObj.Status__c != oldObj.Status__c && newObj.Status__c == '終了'){
                System.debug(newObj);
                if(newObj.EndDatetime__c == null){
                    newObj.EndDatetime__c = Datetime.now();
                }
            }
        }
    }

    /**
     * after insert
     */
    public void onAfterInsert(Map<Id, Visit__c> newMap){
    }

    /**
     * after update
     */
    public void onAfterUpdate(Map<Id, Visit__c> newMap, Map<Id, Visit__c> oldMap){
    }
}