force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>訪問</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{000000}</displayFormat>
        <label>訪問名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>取引先名</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>訪問</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/EndDatetime__c.field-meta.xml
<CustomField>
    <fullName>EndDatetime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>終了時刻</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状態</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>予定</fullName>
                <default>true</default>
                <label>予定</label>
            </value>
            <value>
                <fullName>訪問中</fullName>
            </value>
            <value>
                <fullName>終了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
            <value>
                <fullName>日程変更</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VisitTriggerHandlerTest.cls
@isTest 
public with sharing class VisitTriggerHandlerTest {
    @testSetup 
    public static void testSetup() {
        Account account = new Account();
        account.name = 'Test Account';
        insert account;

        Visit__c visit = new Visit__c();
        visit.Account__c = account.id;
        insert visit;
    }

    @isTest
    public static void test001() {
        Visit__c visit = [select id, name, Status__c, EndDatetime__c from Visit__c order by CreatedDate DESC limit 1];
        System.debug(visit);
        visit.Status__c = '終了';
        
        Test.startTest();
        update visit;
        Test.stopTest();

        Visit__c visitUpdated = [select id, name, Status__c, EndDatetime__c from Visit__c order by CreatedDate DESC limit 1];
        System.debug(visitUpdated);
        Assert.isNotNull(visitUpdated.EndDatetime__c);
    }
}